### ISSUE TITLE
Forte IR could save incorrect selector config

### ISSUE THREAD

**Issue by zhanyuanucb** [asyml/forte#558]
**Describe the bug**
For backward compatibility, Forte allows users to specify selector config via its `__init__` (_e.g._ `RegexNameMatchSelector(select_name=r"passage_\d")`, and more details [here](https://github.com/asyml/forte/blob/master/forte/data/selector.py#L153-L163)). 
However, current implementation sometimes causes Forte IR to save incorrect selector config.

**To Reproduce**
```
import forte
from forte.data.readers import PlainTextReader
from forte.data.selector import RegexNameMatchSelector
from forte.processors.misc import PeriodSentenceSplitter

# Build a simple pipeline
nlp = forte.pipeline.Pipeline()
nlp.set_reader(PlainTextReader())
selector_hit = RegexNameMatchSelector(select_name=r"passage_\d")
nlp.add(PeriodSentenceSplitter(), selector=selector_hit)

```

**Expected behavior**
```
fir = nlp._dump_to_config()

print(selector_hit.select_name)
# output: passage_\d

print(fir['components'][1]['selector']['configs'])
# output: {'reverse_selection': False, 'select_name': None}
# expected: {'reverse_selection': False, 'select_name': 'passage_\d'}

print(selector_hit.configs)
# output: {'reverse_selection': False, 'select_name': None}
# expected: {'reverse_selection': False, 'select_name': 'passage_\d'}

nlp.initialize()

print(selector_hit.configs)
# output: {'reverse_selection': False, 'select_name': 'passage_\d'}
# comment: output as expected after initializing the pipeline

fir = nlp._dump_to_config()
print(fir['components'][1]['selector']['configs'])
# output: {'reverse_selection': False, 'select_name': None}
# expected: {'reverse_selection': False, 'select_name': 'passage_\d'}
# comment: but the IR generated after pipeline initialization is still incorrect
```

**Screenshots**
None

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 16.04
 - Python and Package verions: `python:3.6`

**Additional context**
None

**Comment by zhanyuanucb** [comment]
This line will overwrite whatever config specified in `__init__`.
https://github.com/asyml/forte/blob/257f5d4798c632a67e63a4d549c81f2b3b87b714/forte/pipeline.py#L830

**Comment by hunterhector** [comment]
I think we shouldn't call `initialize` to get around the problem because this step may try to load some resources. 

So the problem is we have passed in the states to the selector, but the pipeline doesn't know about it. The pipeline uses the `selector_config` passed from `add` and `self.default_config` as an internal config. Both of these are not controllable by the `__init__` instance function of the selector, since `add` is outside of the class, and `default_config` is a class method. 

I think about this and cannot come up with a reasonable solution. I think we can settle by claiming in the documentation that passing parameter to the selector `init` is deprecated, and it does not work well with the IR.
