### ISSUE TITLE
AttributeError: 'DataPack' object has no attribute 'to_string'

### ISSUE THREAD

**Issue by munachisonwadike** [asyml/forte#671]
**Issue**
When I try to run the [code for [cord_indexer],](https://github.com/petuum/composing_information_system/blob/main/QA.md), while following the Forte 3-part Tutorial (Part 2) I run the code `python examples/pipeline/indexer/cordindexer.py --data-dir ../cord_data_2021-04-13/document_parses/pdf_json`

But I get an error `AttributeError: 'DataPack' object has no attribute 'to_string'`
What does this mean? Perhaps I am using the incorrect forte version?

**Code versions**

- forte version '0.1.2'
- python 3.6
- python elasticsearch client version '7.11.0'
- elasticsearch server version '7.12.2' (though this may not be the source of the error?)
 
**Screenshots**
![image](https://user-images.githubusercontent.com/22077758/156886621-57188d91-8ee0-448f-ad91-9a14b1c37d44.png)

**Comment by hunterhector** [comment]
Hi, thanks for submitting the issue. 

After taking a quick look, I believe this could be an interplay of multiple versions since many projects are involved. Since both Forte and Forte-wrappers are updated since the post-release. 

1. We find out the new elasticsearch (>8.0) has new API interfaces, we haven't supported that yet. But this is not the problem this time.
2. We need to use Forte and Forte-wrapper with synchronized versions. It looks like you are using an old version of Forte but the new Forte-wrapper code.

I guess there are two ways to solve this, one is to downgrade both to the time where the blog post was written. This will probably work, but not gonna be very sustainable.

Another option is to try to install both Forte and Forte-wrapper from source (i.e. clone the repo and do `pip install .`, following the installation guide). This may introduce other problems, but we can help address those ones too and have the latest code!

**Comment by munachisonwadike** [comment]
Thank you so much for this insightful reply @hunterhector .

Regarding your option number (1): I have attached a screenshot below, from the Forte Readme, which recommends forte-wrappers to be installed from source. I was unable to locate the precise way to install `forte-wrappers` using pip? 

However, the `asyml\forte-wrappers.git` repository releases [link](https://github.com/asyml/forte-wrappers/releases), only has one release. What may be your recommendation for how I can downgrade the forte-wrappers version, so it matches the forte version?


Warm regards,

![image](https://user-images.githubusercontent.com/22077758/156919302-779e2262-313a-438d-ae6e-e9ac84f78e09.png)

**Comment by hunterhector** [comment]
Let's try to install both from source instead since downgrading won't be a stable solution.

https://github.com/asyml/forte#download-and-installation

**Comment by munachisonwadike** [comment]
Hello Hector! 
I installed both from source very carefully, using the version "=="  elasticsearch 7.5.1  here [[link](https://github.com/asyml/forte-wrappers/blob/2c1b2681cf647f40e70b04545d42bc322b9e4192/src/elastic/setup.py#L32)] instead of ">="
However, the we get the same error in the screenshot: `AttributeError: 'DataPack' object has no attribute 'to_string'`. Perhaps we can install a specific fortex elasticsearch version? The line that throws the error in the screenshot is line 134 in `elastic_search_index_processor.py` May there be a particular commit I can revert to for this?
Warm regards,

**Comment by hunterhector** [comment]
For this particular error, the version of  `elasticsearch` should be irrelevant.

The error actually says `DataPack has no to_string`, but we find this line in the source here: https://github.com/asyml/forte/blob/master/forte/data/base_pack.py#L279 

That's why installing Forte from the source should be the right version.

After the installation, can you check whether you can import `DataPack` and refer to its `to_string` function? If not, then it means the wrong version of Forte is installed.

One possible reason is that `setup.py` requires one to use a PIP version instead of a source version (https://github.com/asyml/forte-wrappers/blob/2c1b2681cf647f40e70b04545d42bc322b9e4192/src/elastic/setup.py#L31), that means if you install `forte-wrapper` later, then it will overwrite and use the PIP version. To use the source version, you may need to install Forte from source again.

I am cc'ing to @J007X so he knows the discussion, and he can also see what happens.

**Comment by munachisonwadike** [comment]
Oh great! Sure I think this was indeed the issue that in the process of installing forte-wrappers from source I forgot to install forte from source. I am no longer getting this particular error! Now I am getting a different error of a missing package related to composable_information_system. I have opened an issue here [[link](https://github.com/asyml/forte-wrappers/issues/98)] ..
Warm regards,

**Comment by hunterhector** [comment]
Sounds good. If that's the case, you can consider close this issue if it is resolved.
