### ISSUE TITLE
About downloading NER model

### ISSUE THREAD

**Issue by Dong34** [asyml/forte#789]
**Can not download pretrained NER model**
Hi there! I can not download the pretrained NER model from forte/examples/pipelines/download_models.py. 

It says: ERROR:root:Failed to download model.pkl because of invalid response from https://docs.google.com/uc?export=download&id=1j3i5U1YffYqKTdSbnlsrMAm9j86nLjxC: status_code='404' reason='Not Found'

Do anyone have any idea on how to download the pretrained model? I don't have enough computation power to train the model and I just want to try out the NER funtion.

**Comment by feipenghe** [comment]
It seems that the hyperlink of the model have been removed, and it might no longer recoverable since we don't have the owner's google account. If you want to try out the pipeline, this example have models and datasets to all the valid [hyperlinks](https://github.com/petuum/composing_information_system/blob/main/training.md).
